seed: 1024
resume: False
image_size: 32
num_channels: 3
centered: True
use_geometric: False
beta_min: 0.05
beta_max: 0.2
num_channels_dae: 128
n_mlp: 4
ch_mult: [1, 2, 2, 2]
num_res_blocks: 2
dropout: 0.0
resamp_with_conv: True
conditional: True
fir: True
fir_kernel: [1, 3, 3, 1]
skip_rescale: True
resblock_type: biggan
progressive: none
progressive_input: residual
progressive_combine: sum
fourier_scale: 16.0
not_use_tanh: False
exp: experiment_cifar_default
dataset: cifar10
nz: 100
z_emb_dim: 256
batch_size: 128
num_epoch: 1800
ngf: 64
lr_g: 0.00016
lr_d: 0.000125
beta1: 0.5
beta2: 0.9
no_lr_decay: False
use_ema: True
ema_decay: 0.9999
r1_gamma: 0.02
lazy_reg: 15
save_content: True
save_content_every: 50
save_ckpt_every: 25